timezone:   America/New_York
paginate: 5
paginate_path: "blog/page:num"
markdown: kramdown

name: Hacksburg
description: The blog of Blacksburg's Workshop
url: http://hacksburg.org
# baseurl:    http://hacksburg.org
plugins:
 - jekyll-redirect-from